#pragma once

#include <allegro5/allegro.h>

enum
{
    AXE_EDITOR_EVENT_MOVE_VIEW = ALLEGRO_GET_EVENT_TYPE('M','A','X','E'),
    AXE_EDITOR_EVENT_ZOOM_IN,
    AXE_EDITOR_EVENT_ZOOM_OUT,
    AXE_EDITOR_EVENT_SHOWHIDE_GRID,
    AXE_EDITOR_EVENT_COPY_DATA
};